### ISSUE TITLE
Error while loading mod

### ISSUE THREAD

**Issue by SecretGamerV071** [Lizard-Of-Oz/Inventorio#145] opened 2022-08-06 06:58 UTC
[crash-2022-08-06_12.25.19-fml.txt](https://github.com/Lizard-Of-Oz/Inventorio/files/9274550/crash-2022-08-06_12.25.19-fml.txt)

**Comment by Lizard-Of-Oz** [comment] 2022-08-06 07:03
Duplicate of #139 
tl;dr - You need to download Inventorio 1.8.2 or downgrade Forge

**Closed by Lizard-Of-Oz** 2022-08-06 07:03 UTC
