### ISSUE TITLE
Unknown Crash Report

### ISSUE THREAD

**Issue by Quizer9O8** [Lizard-Of-Oz/Inventorio#46] opened 2021-06-22 11:11 UTC
For some reason I keep getting this crash when launching the game.
I have a couple of mods installed but I can't find the reason why it is crashing now.
Without any other mods or just a few it seems to work just fine.

[Crash report](https://mcpaste.io/8fe851a91e4ca4c2)

**Comment by Lizard-Of-Oz** [comment] 2021-06-22 11:37
Duplicate of #42 (Conflict with Charm)
Same answer:
> Huh, apparently mods conflict due to both trying to inject into the same place in Totem of Undying's behavior.
My fix is coming soon, but you can temporary fix it by setting `TotemFromUtilityBelt` value to `false` in `config/inventorio_shared.json`

**Closed by Lizard-Of-Oz** 2021-06-22 11:37 UTC
